### ISSUE TITLE
export from syntax

### ISSUE THREAD

**Issue by samhh** [gcanti/docs-ts#16]
Using `export { f } from 'm'` syntax with the usual accompanying JSDoc fails with a "missing f documentation" error.

**Comment by gillchristian** [comment]
All the exports are expected to have a JSDoc comment with at least `@since x.y.z` tag.

```ts
export {
  /**
   * @since 0.1.0
   */
  f
} from 'm'
```

Not sure if @gcanti is open to customization on this behavior :thinking: 

I'm working on a fork that adds support for a config to customize these things: https://github.com/gillchristian/docs-ts-extra (is not published yet but I can publish it if you are interested on using it).

**Comment by samhh** [comment]
Ahhh that was me being silly then! I was placing it above the statement but of course this makes more sense, cheers.

I don't mind that limitation, it encouraged me to better document my library. :smile: But yeah it did make adoption harder. It'd make adoption virtually impossible for an established, massive library.

**Comment by gillchristian** [comment]
Glad I was able to help :smile: 

> It'd make adoption virtually impossible for an established, massive library

Hence my fork :sweat_smile:

**Comment by samhh** [comment]
Interesting... this causes the generated signature to change from `f`'s type to `typeof f` :thinking:
