### ISSUE TITLE
Make aux/github link configurable

### ISSUE THREAD

**Issue by StefanoMagrassi** [gcanti/docs-ts#26]
**Do you want to request a _feature_ or report a _bug_?**

Feature

**What is the current behavior?**

In `_config.yml` the `aux_links/github` field is automatically set with package.json's homepage value which can be different from repository url 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://codesandbox.io/ or similar.**

**What is the expected behavior?**

Another field `github` in `docs-ts.json` field that will be used as `aux_links/github` link.

**Which versions of docs-ts, and which browser and OS are affected by this issue? Did this work in previous versions of docs-ts?**

0.6.2

**Comment by IMax153** [comment]
Hey @StefanoMagrassi! I think adding this config property is fine, but would you be okay with using the name `projectHomepage` ?

Since any custom configuration properties provided by the user end up [overriding their default value](https://github.com/gcanti/docs-ts/blob/3a98908f6fd9aa2d47fe23df57bf9422b7f346d1/src/Core.ts#L480), using the same name for the property in the [`Config`](https://github.com/gcanti/docs-ts/blob/3a98908f6fd9aa2d47fe23df57bf9422b7f346d1/src/Config.ts#L30) interface and the property in the [`Setting`](https://github.com/gcanti/docs-ts/blob/3a98908f6fd9aa2d47fe23df57bf9422b7f346d1/src/Config.ts#L45)s just makes things easier.

It isn't difficult to change the name to something else though, if everyone feels strongly!

**Comment by StefanoMagrassi** [comment]
@IMax153 the `projectHomepage` field would be fine
